commerce_cmi.commerce_payment_gateway.cmi_payments_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    api_url:
      type: string
      label: 'Api URL'
    api_key:
      type: string
      label: 'Api Key'
    secret_key:
      type: string
      label: 'Shared Secret'